#pragma once

#include <lake/moon.h>
#ifdef MOON_VULKAN

FN_MOON_LIST_DEVICE_DETAILS(vulkan);
FN_MOON_DEVICE_ASSEMBLY(vulkan);
FN_MOON_DEVICE_DESTRUCTOR(vulkan);
FN_MOON_DEVICE_QUEUE_COUNT(vulkan);
FN_MOON_DEVICE_QUEUE_WAIT_IDLE(vulkan);
FN_MOON_DEVICE_WAIT_IDLE(vulkan);
FN_MOON_DEVICE_SUBMIT_COMMANDS(vulkan);
FN_MOON_DEVICE_PRESENT_FRAMES(vulkan);
FN_MOON_DEVICE_DESTROY_DEFERRED(vulkan);
FN_MOON_DEVICE_HEAP_ASSEMBLY(vulkan);
FN_MOON_DEVICE_HEAP_DESTRUCTOR(vulkan);
FN_MOON_DEVICE_BUFFER_MEMORY_REQUIREMENTS(vulkan);
FN_MOON_DEVICE_TEXTURE_MEMORY_REQUIREMENTS(vulkan);
FN_MOON_DEVICE_MEMORY_REPORT(vulkan);

FN_MOON_CREATE_BUFFER(vulkan);
FN_MOON_CREATE_BUFFER_FROM_HEAP(vulkan);
FN_MOON_CREATE_TEXTURE(vulkan);
FN_MOON_CREATE_TEXTURE_FROM_HEAP(vulkan);
FN_MOON_CREATE_TEXTURE_VIEW(vulkan);
FN_MOON_CREATE_SAMPLER(vulkan);
FN_MOON_CREATE_TLAS(vulkan);
FN_MOON_CREATE_TLAS_FROM_BUFFER(vulkan);
FN_MOON_CREATE_BLAS(vulkan);
FN_MOON_CREATE_BLAS_FROM_BUFFER(vulkan);

FN_MOON_IS_BUFFER_VALID(vulkan);
FN_MOON_IS_TEXTURE_VALID(vulkan);
FN_MOON_IS_TEXTURE_VIEW_VALID(vulkan);
FN_MOON_IS_SAMPLER_VALID(vulkan);
FN_MOON_IS_TLAS_VALID(vulkan);
FN_MOON_IS_BLAS_VALID(vulkan);

FN_MOON_BUFFER_HOST_ADDRESS(vulkan);
FN_MOON_BUFFER_DEVICE_ADDRESS(vulkan);
FN_MOON_TLAS_DEVICE_ADDRESS(vulkan);
FN_MOON_BLAS_DEVICE_ADDRESS(vulkan);

FN_MOON_DESTROY_BUFFER(vulkan);
FN_MOON_DESTROY_TEXTURE(vulkan);
FN_MOON_DESTROY_TEXTURE_VIEW(vulkan);
FN_MOON_DESTROY_SAMPLER(vulkan);
FN_MOON_DESTROY_TLAS(vulkan);
FN_MOON_DESTROY_BLAS(vulkan);

FN_MOON_TIMELINE_QUERY_POOL_ASSEMBLY(vulkan);
FN_MOON_TIMELINE_QUERY_POOL_DESTRUCTOR(vulkan);
FN_MOON_TIMELINE_SEMAPHORE_ASSEMBLY(vulkan);
FN_MOON_TIMELINE_SEMAPHORE_DESTRUCTOR(vulkan);
FN_MOON_BINARY_SEMAPHORE_ASSEMBLY(vulkan);
FN_MOON_BINARY_SEMAPHORE_DESTRUCTOR(vulkan);

FN_MOON_COMPUTE_PIPELINES_ASSEMBLY(vulkan);
FN_MOON_COMPUTE_PIPELINE_DESTRUCTOR(vulkan);
FN_MOON_WORK_GRAPH_PIPELINES_ASSEMBLY(vulkan);
FN_MOON_WORK_GRAPH_PIPELINE_DESTRUCTOR(vulkan);
FN_MOON_RASTER_PIPELINES_ASSEMBLY(vulkan);
FN_MOON_RASTER_PIPELINE_DESTRUCTOR(vulkan);
FN_MOON_RAY_TRACING_PIPELINES_ASSEMBLY(vulkan);
FN_MOON_RAY_TRACING_PIPELINE_DESTRUCTOR(vulkan);

FN_MOON_SWAPCHAIN_ASSEMBLY(vulkan);
FN_MOON_SWAPCHAIN_DESTRUCTOR(vulkan);
FN_MOON_SWAPCHAIN_WAIT_FOR_NEXT_FRAME(vulkan);
FN_MOON_SWAPCHAIN_ACQUIRE_NEXT_IMAGE(vulkan);
FN_MOON_SWAPCHAIN_CURRENT_ACQUIRE_SEMAPHORE(vulkan);
FN_MOON_SWAPCHAIN_CURRENT_PRESENT_SEMAPHORE(vulkan);
FN_MOON_SWAPCHAIN_CURRENT_CPU_TIMELINE_VALUE(vulkan);
FN_MOON_SWAPCHAIN_CURRENT_TIMELINE_PAIR(vulkan);
FN_MOON_SWAPCHAIN_GPU_TIMELINE_SEMAPHORE(vulkan);
FN_MOON_SWAPCHAIN_SET_PRESENT_MODE(vulkan);
FN_MOON_SWAPCHAIN_RESIZE(vulkan);

FN_MOON_COMMAND_RECORDER_ASSEMBLY(vulkan);
FN_MOON_COMMAND_RECORDER_DESTRUCTOR(vulkan);
FN_MOON_STAGED_COMMAND_LIST_ASSEMBLY(vulkan);
FN_MOON_STAGED_COMMAND_LIST_DESTRUCTOR(vulkan);

FN_MOON_CMD_COPY_BUFFER(vulkan);
FN_MOON_CMD_COPY_BUFFER_TO_TEXTURE(vulkan);
FN_MOON_CMD_COPY_TEXTURE_TO_BUFFER(vulkan);
FN_MOON_CMD_COPY_TEXTURE(vulkan);
FN_MOON_CMD_BLIT_TEXTURE(vulkan);
FN_MOON_CMD_RESOLVE_TEXTURE(vulkan);
FN_MOON_CMD_CLEAR_BUFFER(vulkan);
FN_MOON_CMD_CLEAR_TEXTURE(vulkan);
FN_MOON_CMD_DESTROY_BUFFER_DEFERRED(vulkan);
FN_MOON_CMD_DESTROY_TEXTURE_DEFERRED(vulkan);
FN_MOON_CMD_DESTROY_TEXTURE_VIEW_DEFERRED(vulkan);
FN_MOON_CMD_DESTROY_SAMPLER_DEFERRED(vulkan);
FN_MOON_CMD_BUILD_ACCELERATION_STRUCTURES(vulkan);
FN_MOON_CMD_ROOT_CONSTANTS(vulkan);
FN_MOON_CMD_SET_COMPUTE_PIPELINE(vulkan);
FN_MOON_CMD_SET_RASTER_PIPELINE(vulkan);
FN_MOON_CMD_SET_RAY_TRACING_PIPELINE(vulkan);
FN_MOON_CMD_SET_WORK_GRAPH_PIPELINE(vulkan);
FN_MOON_CMD_SET_VIEWPORT(vulkan);
FN_MOON_CMD_SET_SCISSOR(vulkan);
FN_MOON_CMD_SET_RASTERIZATION_SAMPLES(vulkan);
FN_MOON_CMD_SET_DEPTH_BIAS(vulkan);
FN_MOON_CMD_SET_INDEX_BUFFER(vulkan);
FN_MOON_CMD_BARRIERS_AND_TRANSITIONS(vulkan);
FN_MOON_CMD_BEGIN_RENDERPASS(vulkan);
FN_MOON_CMD_END_RENDERPASS(vulkan);
FN_MOON_CMD_WRITE_TIMESTAMPS(vulkan);
FN_MOON_CMD_RESOLVE_TIMESTAMPS(vulkan);
FN_MOON_CMD_BEGIN_LABEL(vulkan);
FN_MOON_CMD_END_LABEL(vulkan);
FN_MOON_CMD_DISPATCH(vulkan);
FN_MOON_CMD_DISPATCH_INDIRECT(vulkan);
FN_MOON_CMD_DISPATCH_GRAPH(vulkan);
FN_MOON_CMD_DISPATCH_GRAPH_INDIRECT(vulkan);
FN_MOON_CMD_DISPATCH_GRAPH_INDIRECT_COUNT(vulkan);
FN_MOON_CMD_DRAW(vulkan);
FN_MOON_CMD_DRAW_INDEXED(vulkan);
FN_MOON_CMD_DRAW_INDIRECT(vulkan);
FN_MOON_CMD_DRAW_INDIRECT_COUNT(vulkan);
FN_MOON_CMD_DRAW_MESH_TASKS(vulkan);
FN_MOON_CMD_DRAW_MESH_TASKS_INDIRECT(vulkan);
FN_MOON_CMD_DRAW_MESH_TASKS_INDIRECT_COUNT(vulkan);
FN_MOON_CMD_TRACE_RAYS(vulkan);
FN_MOON_CMD_TRACE_RAYS_INDIRECT(vulkan);

struct moon_adapter_impl {
    moon_interface_impl                 interface;
};

struct moon_device_impl {
    moon_device_header                  header;
};

struct moon_device_heap_impl {
    moon_device_heap_header             header;
};

struct moon_timeline_query_poop_impl {
    moon_timeline_query_pool_header     header;
};

struct moon_timeline_semaphore_impl {
    moon_timeline_semaphore_header      header;
};

struct moon_binary_semaphore_impl {
    moon_binary_semaphore_header        header;
};

struct moon_compute_pipeline_impl {
    moon_compute_pipeline_header        header;
};

struct moon_work_graph_pipeline_impl {
    moon_work_graph_pipeline_header     header;
};

struct moon_raster_pipeline_impl {
    moon_raster_pipeline_header         header;
};

struct moon_ray_tracing_pipeline_impl {
    moon_ray_tracing_pipeline_header    header;
};

struct moon_swapchain_impl {
    moon_swapchain_header               header;
};

struct moon_command_recorder_impl {
    moon_command_recorder_header        header;
};

struct moon_staged_command_list_impl {
    moon_staged_command_list_header     header;
};

#endif /* MOON_VULKAN */
